[package]
name = "base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
rocket = "0.5.0-rc.1"
sled = "0.34.7"
tungstenite = "0.17.2"
